sudo: false
language: java
jdk:
  - oraclejdk8
  
before_install:
 - chmod +x gradlew

script: "./gradlew -q  clean test assemble"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:  "build/libs/RestAssuredExample-*.jar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
