sudo: false
language: java
jdk:
  - oraclejdk8
  
before_install:
 - chmod +x gradlew

script: "./gradlew -q  clean test assemble"

before_deploy:
  - export RELEASE_FILE=$(ls build/libs/RestAssuredExample-*.jar)
  - echo "deploying $RELEASE_FILE to GitHub releases"
  
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:  $RELEASE_FILE
  skip_cleanup: true
  overwrite: true
  on:
    tags: false
